@extends('layouts.admin')
@section('title', $article->exists ? '编辑文章' : '新建文章')
@section('content')
<div class="admin-heading"><div><p class="eyebrow">ARTICLE EDITOR</p><h1>{{ $article->exists ? '编辑文章' : '新建文章' }}</h1></div>@if($article->exists && $article->isPublic())<a class="button button-quiet" href="{{ route('articles.show', $article->slug) }}">查看公开页</a>@endif</div>
<form method="post" action="{{ $article->exists ? route('admin.articles.update', $article) : route('admin.articles.store') }}" class="editor-form">@csrf @if($article->exists) @method('PATCH') @endif
    <div class="editor-main"><label>标题<input name="title" value="{{ old('title', $revision?->title) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $article->slug) }}" placeholder="laravel-release-notes" required><small>只使用小写字母、数字和连字符；变更后旧地址会写入 301 重定向。</small></label><label>摘要<textarea name="excerpt" rows="3">{{ old('excerpt', $revision?->excerpt) }}</textarea></label><label>正文 Markdown<textarea name="markdown" rows="24" required>{{ old('markdown', $revision?->markdown) }}</textarea></label></div>
    <aside class="editor-side"><label>标签<input name="tags[]" value="{{ old('tags.0', $article->tags?->pluck('name')->implode(', ')) }}" placeholder="Laravel, 部署, AI"></label><label>SEO 标题<input name="seo_title" value="{{ old('seo_title', $revision?->seo_title) }}"></label><label>SEO 描述<textarea name="seo_description" rows="5">{{ old('seo_description', $revision?->seo_description) }}</textarea></label><label>验证状态<select name="verification_status"><option value="review_required" @selected(old('verification_status', $revision?->verification_status ?: 'review_required') === 'review_required')>需复核</option><option value="valid" @selected(old('verification_status', $revision?->verification_status) === 'valid')>有效</option><option value="outdated" @selected(old('verification_status', $revision?->verification_status) === 'outdated')>已过时</option></select></label><button class="button button-primary" type="submit">保存草稿</button><button class="button button-quiet" formaction="{{ route('admin.articles.preview') }}" formmethod="post" type="submit">预览</button>@if($article->exists && $article->draftRevision)<button class="button button-publish" formaction="{{ route('admin.articles.publish', $article) }}" type="submit" onclick="return confirm('确认发布当前草稿修订？')">发布当前修订</button>@endif</aside>
</form>
@if($article->exists)<form method="post" action="{{ route('admin.articles.archive', $article) }}" class="danger-form">@csrf<button type="submit" onclick="return confirm('确认归档？')">归档文章</button></form>@endif
@endsection
